"""empty message

Revision ID: 02f39724427a
Revises: e313a246de80
Create Date: 2017-08-23 10:41:04.076806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f39724427a'
down_revision = 'e313a246de80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_form', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_form', 'created_date')
    # ### end Alembic commands ###
