"""empty message

Revision ID: 0b0bb1cd6f5d
Revises: b5ec0ba42af3
Create Date: 2017-08-20 12:20:12.851455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0bb1cd6f5d'
down_revision = 'b5ec0ba42af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_emails_pkey'),
    sa.UniqueConstraint('email', name='users_emails_email_key'),
    sa.UniqueConstraint('email1', name='users_emails_email1_key'),
    sa.UniqueConstraint('user_id', name='users_emails_user_id_key')
    )
    # ### end Alembic commands ###
