"""empty message

Revision ID: 389d93b40de8
Revises: 02f39724427a
Create Date: 2017-08-25 09:08:04.637729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389d93b40de8'
down_revision = '02f39724427a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_playlists', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_playlists', 'updated_date')
    # ### end Alembic commands ###
