"""empty message

Revision ID: 810ab22346a5
Revises: d456ddc4239c
Create Date: 2017-08-21 20:41:51.738801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ab22346a5'
down_revision = 'd456ddc4239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_playlists', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_playlists', 'created_at')
    # ### end Alembic commands ###
