"""empty message

Revision ID: 9c3cd4fc5277
Revises: 2e94a723780e
Create Date: 2017-08-23 10:06:16.658253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3cd4fc5277'
down_revision = '2e94a723780e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_playlists', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('user_playlists', 'created_at')
    op.add_column('user_refresh_token', sa.Column('stored_date', sa.DateTime(), nullable=True))
    op.drop_column('user_refresh_token', 'stored_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_refresh_token', sa.Column('stored_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_refresh_token', 'stored_date')
    op.add_column('user_playlists', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_playlists', 'created_date')
    # ### end Alembic commands ###
