"""empty message

Revision ID: cb1c475abf02
Revises: 421f90cb4d60
Create Date: 2017-08-20 12:15:48.466886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1c475abf02'
down_revision = '421f90cb4d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_emails', sa.Column('email1', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users_emails', ['email1'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_emails', type_='unique')
    op.drop_column('users_emails', 'email1')
    # ### end Alembic commands ###
