"""empty message

Revision ID: d456ddc4239c
Revises: da8a130fdea8
Create Date: 2017-08-21 15:40:16.136120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd456ddc4239c'
down_revision = 'da8a130fdea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_playlists', sa.Column('playlist_name', sa.String(), nullable=True))
    op.add_column('user_playlists', sa.Column('playlist_seed', sa.String(), nullable=True))
    op.add_column('user_playlists', sa.Column('seed_attributes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_playlists', 'seed_attributes')
    op.drop_column('user_playlists', 'playlist_seed')
    op.drop_column('user_playlists', 'playlist_name')
    # ### end Alembic commands ###
