"""empty message

Revision ID: da8a130fdea8
Revises: c331c18b1ad3
Create Date: 2017-08-21 14:43:52.170956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8a130fdea8'
down_revision = 'c331c18b1ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_refresh_token_stored_on_key', 'user_refresh_token', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_refresh_token_stored_on_key', 'user_refresh_token', ['stored_on'])
    # ### end Alembic commands ###
