"""empty message

Revision ID: f63ab640fc9d
Revises: dbf5ebc4e8c4
Create Date: 2017-08-20 12:42:05.134612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63ab640fc9d'
down_revision = 'dbf5ebc4e8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('users_refresh_tokens')
    op.drop_table('users_emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_emails_pkey'),
    sa.UniqueConstraint('email', name='users_emails_email_key'),
    sa.UniqueConstraint('email1', name='users_emails_email1_key'),
    sa.UniqueConstraint('user_id', name='users_emails_user_id_key')
    )
    op.create_table('users_refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_refresh_tokens_pkey'),
    sa.UniqueConstraint('refresh_token', name='users_refresh_tokens_refresh_token_key'),
    sa.UniqueConstraint('user_id', name='users_refresh_tokens_user_id_key')
    )
    op.drop_table('user_refresh_token')
    # ### end Alembic commands ###
